---
output:
  pdf_document: default
  html_document: default
---

```{r}
rm(list = ls())
```

```{r, warning=FALSE}
library(leaflet.extras)
library(sp)
library(leaflet)
library(tidyverse)
library(gstat)
library(sf)
library(readr)
library(spatstat)
library(maptools)
library(dplyr)
```


```{r}
#importing necessary files from GitHub

collisionsfile="https://raw.githubusercontent.com/JustinBrassard/4GA3_Project_And_Proposal/main/data/Motor%20Vehicle%20Collisions/Motor%20Vehicle%20Collisions%20with%20KSI%20Data%20True.csv?token=AS22SR2ZGZO34O7CM56XBFTANDP44"

fullcollisionsfile = "https://raw.githubusercontent.com/JustinBrassard/4GA3_Project_And_Proposal/main/data/Motor%20Vehicle%20Collisions/Full_Collisions.csv"

kidcollisionsfile = "https://raw.githubusercontent.com/JustinBrassard/4GA3_Project_And_Proposal/main/data/Motor%20Vehicle%20Collisions/Kids%20Full%20Collisions%20-%20Motor%20Vehicle%20Collisions%20with%20KSI%20Data.csv"

zonesfile="https://raw.githubusercontent.com/JustinBrassard/4GA3_Project_And_Proposal/main/data/Stationary%20Sign%20locations/Stationary%20Sign%20Locations%20True%20-%20Stationary%20Sign%20locations.csv?token=AS22SR3YXJ3MMPTFKRTZFIDANDQKW"

schoolsfile="https://raw.githubusercontent.com/JustinBrassard/4GA3_Project_And_Proposal/main/data/point-school-locations-wgs84/School%20Locations%20True%20-%20School%20locations-all%20types%20data.csv?token=AS22SR3J4NEF54PS3OOARYTANDQOY"

boundsfile <- "https://raw.githubusercontent.com/JustinBrassard/4GA3_Project_And_Proposal/main/data/Toronto%20Boundary%20Points%20UTM15N/Toronto_Points.csv"


Motor_Vehicle_Collisions_with_KSI_Data_True<-read_csv(url(collisionsfile))
Full_Collisions<-read_csv(url(fullcollisionsfile))
Kid_Collisions<-read_csv(url(kidcollisionsfile))

Stationary_Sign_Locations_True<-read_csv(url(zonesfile))
School_Locations_True<-read_csv(url(schoolsfile))

Toronto_Points<-read_csv(url(boundsfile))
```

```{r}
#separation of 'geometry' column into two lng & lat columns for main data sets
School_Zones <- Stationary_Sign_Locations_True %>%
  separate(geometry, into = c('lng', 'lat'), sep = ', ')
Schools <- School_Locations_True %>%
  separate(geometry, into = c('lng', 'lat'), sep = ', ')

Collisions <- Motor_Vehicle_Collisions_with_KSI_Data_True %>%
  separate(geometry, into = c('lng', 'lat'), sep = ', ')
Full_Collisions <- Full_Collisions %>%
  separate(geometry, into = c('lng', 'lat'), sep = ', ')
Kid_Collisions <- Kid_Collisions %>%
  separate(geometry, into = c('lng', 'lat'), sep = ', ')
```

```{r}
#df to sf conversion of main data sets
School_Zones.sf <- st_as_sf(School_Zones, coords = c("lng", "lat"))
Schools.sf <- st_as_sf(Schools, coords = c("lng", "lat"))

Collisions.sf <- st_as_sf(Collisions, coords = c("lng", "lat"))
```

```{r}
#test plots
ggplot(data = Collisions.sf) +
  geom_sf() +
  labs(title = "Collisions")

ggplot(data = School_Zones.sf) +
  geom_sf() +
  labs(title = "School Zone Locations")

ggplot(data = Schools.sf) +
  geom_sf() +
  labs(title = "School Locations")

ggplot() +
  geom_sf(data = Schools.sf, color = "grey") +
  geom_sf(data = School_Zones.sf, color = "yellow") +
  geom_sf(data = Collisions.sf, color = "red") +
  labs(title = "Collisions & Schools & School Zones")
```

```{r}
#icon creation for main leaflet (TEST)
schoolIcon <- makeIcon(
  iconUrl = "https://www.freeiconspng.com/uploads/school-house-icon-16.png",
  iconWidth = 20, iconHeight = 20
)
smallschoolIcon <- makeIcon(
  iconUrl = "https://www.freeiconspng.com/uploads/school-house-icon-16.png",
  iconWidth = 10, iconHeight = 10
)
zonesIcon <- makeIcon(
  iconUrl = "https://www.freeiconspng.com/uploads/school-icon-png-40.png",
  iconWidth = 20, iconHeight = 20
)
collisionsIcon <- makeIcon(
  iconUrl = "https://www.freeiconspng.com/uploads/-alert-attention-danger-exclamation-safety-warning-icon--icon--33.png",
  iconWidth = 20, iconHeight = 20
)
smallzonesIcon <- makeIcon(
  iconUrl = "https://www.freeiconspng.com/uploads/school-icon-png-40.png",
  iconWidth = 10, iconHeight = 10
)
```

```{r}
#Main data sets leaflet (TEST)
overview.map <- leaflet() %>% addTiles() %>%
  addMarkers(data = Collisions.sf, icon = collisionsIcon) %>%
  addMarkers(data = School_Zones.sf, icon = zonesIcon) %>%
  addMarkers(data = Schools.sf, icon = schoolIcon)

overview.map
```






HEATMAP ANALYSIS
```{r}
#leaflet map containing the point locations of 2019 collisions
collisions.map <- leaflet() %>% addTiles() %>%
  addMarkers(data = Collisions.sf, icon = collisionsIcon)

collisions.map

#setting necessary coords as numeric values
Collisions$lng <- as.numeric(Collisions$lng)
Collisions$lat <- as.numeric(Collisions$lat)

Full_Collisions$lng <- as.numeric(Full_Collisions$lng)
Full_Collisions$lat <- as.numeric(Full_Collisions$lat)

Kid_Collisions$lng <- as.numeric(Kid_Collisions$lng)
Kid_Collisions$lat <- as.numeric(Kid_Collisions$lat)

#creation of 2019 collisions heatmap
collisions.hmap <- leaflet(data = Collisions) %>% 
  setView(lng = -79.3, lat = 43.65, zoom = 10) %>% 
  addTiles()


#2019 collisions heatmap 
collisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 17)

#creation of kid collisions heatmap
kid_collisions.hmap <- leaflet(data = Kid_Collisions) %>% 
  setView(lng = -79.3, lat = 43.65, zoom = 10) %>% 
  addTiles()

#kid collisions hmap
kid_collisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 17)
```


```{r}
#2019 collisions heatmap with school zone markers 
collisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 16) %>%
              addMarkers(data = School_Zones.sf, icon = smallzonesIcon)

#2019 collisions heatmap with school locations 
collisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 16) %>%
              addMarkers(data = Schools.sf, icon = smallschoolIcon)
```


```{r}
#2006 – 2019 collisions heatmap with school zone markers 
fullcollisions.hmap <- leaflet(data = Full_Collisions) %>% 
  setView(lng = -79.3, lat = 43.65, zoom = 10) %>% 
  addTiles()

fullcollisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 16) %>%
              addMarkers(data = School_Zones.sf, icon = smallzonesIcon)

#2006 – 2019 collisions heatmap with school location markers
fullcollisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 16) %>%
              addMarkers(data = Schools.sf, icon = smallschoolIcon)

```


```{r}
#2006 – 2019 collisions involving only pedestrian and cyclist collisions involving people aged 0-19 heatmap with school zone markers
kidcollisions.hmap <- leaflet(data = Kid_Collisions) %>% 
  setView(lng = -79.3, lat = 43.65, zoom = 10) %>% 
  addTiles()

kidcollisions.hmap %>% addHeatmap(lng = ~lng, lat = ~lat, intensity = 1,
             blur = 40, max = 1, radius = 16) %>%
              addMarkers(data = School_Zones.sf, icon = smallzonesIcon)
```




QUADRAT ANALYSIS

```{r}
#Conversion of WGS84 lat and lng points to corresponding UTM17N eastings and northings
CollisionsXY <- Collisions %>%
  select(lng, lat)

CollisionsXY$lat <- as.numeric(CollisionsXY$lat)
CollisionsXY$lng <- as.numeric(CollisionsXY$lng)

coordinates(CollisionsXY) <- c("lng", "lat")
proj4string(CollisionsXY) <- CRS("+proj=longlat +datum=WGS84")
Collisions.trfm <- spTransform(CollisionsXY, CRS("+proj=utm +zone=17 ellps=WGS84"))
CollisionsPCS <- as(Collisions.trfm, "SpatialPoints")

#USE FOR QUADRAT
CollisionsPCS.sf <- st_as_sf(CollisionsPCS)
Collisionscopy.sf <- Collisions.sf
Collisionscopy.sf[, "geometry"] <- CollisionsPCS.sf[,"geometry"]

#USE 'CollisionsPCS.sf' FOR QUADRAT
CollisionsPCS.sf <- Collisionscopy.sf
#######################################################################################

SchoolsXY <- Schools %>%
  select(lng, lat)

SchoolsXY$lat <- as.numeric(SchoolsXY$lat)
SchoolsXY$lng <- as.numeric(SchoolsXY$lng)

coordinates(SchoolsXY) <- c("lng", "lat")
proj4string(SchoolsXY) <- CRS("+proj=longlat +datum=WGS84")
Schools.trfm <- spTransform(SchoolsXY, CRS("+proj=utm +zone=17 ellps=WGS84"))
SchoolsPCS <- as(Schools.trfm, "SpatialPoints")


SchoolsPCS.sf <- st_as_sf(SchoolsPCS)
Schoolscopy.sf <- Schools.sf
Schoolscopy.sf[, "geometry"] <- SchoolsPCS.sf[,"geometry"]

#USE 'SchoolsPCS.sf' FOR QUADRAT
SchoolsPCS.sf <- Schoolscopy.sf
#######################################################################################

School_ZonesXY <- School_Zones %>%
  select(lng, lat)

School_ZonesXY$lat <- as.numeric(School_ZonesXY$lat)
School_ZonesXY$lng <- as.numeric(School_ZonesXY$lng)

coordinates(School_ZonesXY) <- c("lng", "lat")
proj4string(School_ZonesXY) <- CRS("+proj=longlat +datum=WGS84")
School_Zones.trfm <- spTransform(School_ZonesXY, CRS("+proj=utm +zone=17 ellps=WGS84"))
School_ZonesPCS <- as(School_Zones.trfm, "SpatialPoints")

#USE FOR QUADRAT
School_ZonesPCS.sf <- st_as_sf(School_ZonesPCS)
zonescopy.sf <- School_Zones.sf
zonescopy.sf[, "geometry"] <- School_ZonesPCS.sf[,"geometry"]

#USE 'SchoolsPCS.sf' FOR QUADRAT
School_ZonesPCS.sf <- zonescopy.sf
#######################################################################################
```

```{r}
#read shapefile
toronto_boundary <- st_read(
  "data/toronto-boundary-wgs84/citygcs_regional_mun_wgs84.shp")

#convert polygon to group of lines
toronto.lines = st_cast(toronto_boundary,"LINESTRING")

#convert lines to points
toronto_points <- st_cast(toronto.lines, to = "POINT")

toronto_points <- as.data.frame(toronto_points)
#AT THIS POINT I EXTRACTED toronto_points AS A CSV AND SEPARATED THE LNG AND LAT IN SHEETS (Toronto_Points)
```
```{r}
#there's an error here. I cut the code block here since the previous part worked.
#converting points from WGS84 to UTM17N
coordinates(Toronto_Points) <- c("LNG", "LAT")
proj4string(Toronto_Points) <- CRS("+proj=longlat +datum=WGS84")
Toronto_Points.trfm <- spTransform(Toronto_Points, CRS("+proj=utm +zone=17 ellps=WGS84"))
Toronto_Points <- as(Toronto_Points.trfm, "SpatialPoints")
```

```{r}
Toronto_Points.df <- as.data.frame(Toronto_Points)

#convert Toronto boundary points to polygon 
poly <- Polygon(Toronto_Points.df)
poly2 <- Polygons(list(poly),1)
Toronto_Poly <- SpatialPolygons(list(poly2))
plot(Toronto_Poly)

#convert polygon to simple feature and assign as window
Toronto_Poly <- st_as_sf(Toronto_Poly)
Toronto.owin <- as.owin(as(Toronto_Poly, "Spatial"))
```






Quadrat Test for Collisions
```{r}
collisions.ppp <- as.ppp(st_coordinates(CollisionsPCS.sf), W = Toronto.owin)
summary(collisions.ppp)
plot(collisions.ppp)
```

```{r}
q_count_coll <- quadratcount(collisions.ppp, nx = 3, ny = 3)
table(q_count_coll)
```

```{r}
plot(q_count_coll)
```

```{r}
q_test_coll <- quadrat.test(collisions.ppp, nx = 3, ny = 3)
q_test_coll
```

```{r}
plot(q_test_coll)
```





#Quadrat Test for Speed Signs

```{r}
speedsigns.ppp <- as.ppp(st_coordinates(School_ZonesPCS.sf), W = Toronto.owin)
summary(speedsigns.ppp)
plot(speedsigns.ppp)
```

```{r}
q_count_sss <- quadratcount(speedsigns.ppp, nx = 3, ny = 3)
table(q_count_sss)
```

```{r}
plot(q_count_sss)
plot(q_count_coll)
```

```{r}
q_test_sss <- quadrat.test(speedsigns.ppp, nx = 3, ny = 3)
q_test_sss
```

```{r}
plot(q_test_sss)
```






Quadrat Test for Schools

```{r}
Schools.ppp <- as.ppp(st_coordinates(SchoolsPCS.sf), W = Toronto.owin)
summary(Schools.ppp)
plot(Schools.ppp)
```

```{r}
q_count_School <- quadratcount(Schools.ppp, nx = 5, ny = 6)
q_count_coll <- quadratcount(collisions.ppp, nx = 5, ny = 6)
q_count_sss <- quadratcount(speedsigns.ppp, nx = 5, ny = 6)
table(q_count_School)
```

```{r}
plot(q_count_School)
plot(q_count_sss)
plot(q_count_coll)
```

```{r}
q_test_School <- quadrat.test(Schools.ppp, nx = 3, ny = 3)
q_test_School
```

```{r}
plot(q_test_School)
```







Buffers

```{r 0.5-schools-collision-buffer, echo=FALSE, warning=FALSE, message=FALSE}
#similar question from stack exchange: https://gis.stackexchange.com/questions/292327/creating-buffers-around-points-and-merging-with-spatialpolygonsdataframe-to-crea
#prerequisites: load sf and sp libraries (done)
#convert data frame and/or sp to sf using st_as_sf (done)
#set crs using st_crs

st_crs(Coll_km) = st_crs(SZ_km)
#convert to metric using 'target_km = st_transform(target, "+proj=utm +zone=17N +datum=WGS84 +units=km")'
#plot to make sure nothing has gone wrong
SZ_km = st_transform(School_ZonesPCS.sf, "+proj=utm +zone=17N +datum=WGS84 +units=km")
#SZ_km

Coll_km = st_transform(CollisionsPCS.sf, "+proj=utm +zone=17N +datum=WGS84 +units=km")
#Coll_km

Schools_km = st_transform(SchoolsPCS.sf, "+proj=utm +zone=17N +datum=WGS84 +units=km")
#Schools_km

#create 0.5km buffer
School_buffer0.5 = st_buffer(Schools_km, 0.5)
School_Coll0.5 = st_intersection(School_buffer0.5, Coll_km)

#read output
dim(School_Coll0.5)

School_Coll0.5.sf <- st_as_sf(School_Coll0.5)

ggplot() +
  geom_sf(data = School_Coll0.5.sf, color = "red")
```

```{r 0.25-school-coll-buffer, echo=FALSE}
#create a 0.25km schools v collisions buffer
School_buffer0.25 = st_buffer(Schools_km, 0.25)
School_Coll0.25 = st_intersection(School_buffer0.25, Coll_km)

#read output
dim(School_Coll0.25)

School_Coll0.25.sf <- st_as_sf(School_Coll0.25)

ggplot() +
  geom_sf(data = School_Coll0.25.sf, color = "red")
```

```{r 0.1-school-coll-buffer, echo=FALSE}
#create a 0.1km schools v collisions buffer
School_buffer0.1 = st_buffer(Schools_km, 0.1)
School_Coll0.1 = st_intersection(School_buffer0.1, Coll_km)

#read output
dim(School_Coll0.1)

School_Coll0.1.sf <- st_as_sf(School_Coll0.1)

ggplot() +
  geom_sf(data = School_Coll0.1.sf, color = "red")
```

```{r 0.5-school-speedsign-buffer, echo=FALSE}
#create a 0.5km schools v speed signs buffer
School_buffer0.5 = st_buffer(Schools_km, 0.5)
School_speed0.5 = st_intersection(School_buffer0.5, SZ_km)

#read output
dim(School_speed0.5)

School_speed0.5.sf <- st_as_sf(School_speed0.5)

ggplot() +
  geom_sf(data = School_speed0.5.sf, color = "green")
```

```{r 0.25-school-speedsign-buffer, echo=FALSE}
#create a 0.25km schools v speed signs buffer
School_buffer0.25 = st_buffer(Schools_km, 0.25)
School_speed0.25 = st_intersection(School_buffer0.25, SZ_km)

#read output
dim(School_speed0.25)

School_speed0.25.sf <- st_as_sf(School_speed0.25)

ggplot() +
  geom_sf(data = School_speed0.25.sf, color = "green")
```

```{r 0.1-school-speedsign-buffer, echo=FALSE}
#create a 0.1km schools v speed signs buffer
School_buffer0.1 = st_buffer(Schools_km, 0.1)
School_speed0.1 = st_intersection(School_buffer0.1, SZ_km)

#read output
dim(School_speed0.1)

School_speed0.1.sf <- st_as_sf(School_speed0.1)

ggplot() +
  geom_sf(data = School_speed0.1.sf, color = "green")
```

```{r 0.5-schoolzone-coll-buffer, echo=FALSE}
#create 0.5km school zone v collisions buffer
SZ_buffer0.5 = st_buffer(SZ_km, 0.5)
SZ_Coll0.5 = st_intersection(SZ_buffer0.5, Coll_km)

#read output
dim(SZ_Coll0.5)

SZ_Coll0.5.sf <- st_as_sf(SZ_Coll0.5)

ggplot() +
  geom_sf(data = SZ_Coll0.5.sf, color = "black")
```

```{r 0.25-schoolzone-coll-buffer, echo=FALSE}
#create 0.25km school zone v collisions buffer
SZ_buffer0.25 = st_buffer(SZ_km, 0.25)
SZ_Coll0.25 = st_intersection(SZ_buffer0.25, Coll_km)

#read output
dim(SZ_Coll0.25)

SZ_Coll0.25.sf <- st_as_sf(SZ_Coll0.25)

ggplot() +
  geom_sf(data = SZ_Coll0.25.sf, color = "black")
```

```{r 0.1-schoolzone-coll-buffer, echo=FALSE}
#create 0.1km school zone v collisions buffer
SZ_buffer0.1 = st_buffer(SZ_km, 0.1)
SZ_Coll0.1 = st_intersection(SZ_buffer0.1, Coll_km)

#read output
dim(SZ_Coll0.1)

SZ_Coll0.1.sf <- st_as_sf(SZ_Coll0.1)

ggplot() +
  geom_sf(data = SZ_Coll0.1.sf, color = "black")
```

```{r 0.5-total, echo=FALSE}
ggplot() +
  geom_sf(data = School_Coll0.5.sf, color = "red") +
  geom_sf(data = School_speed0.5.sf, color = "green") +
  geom_sf(data = SZ_Coll0.5.sf, color = "black")
dim(School_Coll0.5)
dim(School_speed0.5)
dim(SZ_Coll0.5)
```

```{r 0.25-total, echo=FALSE}
ggplot() +
  geom_sf(data = School_Coll0.25.sf, color = "red") +
  geom_sf(data = School_speed0.25.sf, color = "green") +
  geom_sf(data = SZ_Coll0.25.sf, color = "black")
dim(School_Coll0.25)
dim(School_speed0.25)
dim(SZ_Coll0.25)
```

```{r 0.1-total, echo=FALSE}
ggplot() +
  geom_sf(data = School_Coll0.1.sf, color = "red") +
  geom_sf(data = School_speed0.1.sf, color = "green") +
  geom_sf(data = SZ_Coll0.1.sf, color = "black")

School_Coll0.1.sf
SZ_Coll0.1.sf$address
dim(School_Coll0.1)
dim(School_speed0.1)
dim(SZ_Coll0.1)
```

